// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv_rOXHJiTUbw3IxvOpLp9PCJAe3bZ8is',
    appId: '1:443562001040:web:d3cdaf201b755aa1a88e15',
    messagingSenderId: '443562001040',
    projectId: 'flutter-my-app-d1f4c',
    authDomain: 'flutter-my-app-d1f4c.firebaseapp.com',
    storageBucket: 'flutter-my-app-d1f4c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIC8TQ0QPvXuq3eaBq7C9JvoyQfoX-6Q0',
    appId: '1:443562001040:android:2d1f12df36cdeaa2a88e15',
    messagingSenderId: '443562001040',
    projectId: 'flutter-my-app-d1f4c',
    storageBucket: 'flutter-my-app-d1f4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbA700j-7nMDoi4JJlusKE2QV8sWBnBpw',
    appId: '1:443562001040:ios:ceb62bf1af61291aa88e15',
    messagingSenderId: '443562001040',
    projectId: 'flutter-my-app-d1f4c',
    storageBucket: 'flutter-my-app-d1f4c.appspot.com',
    iosClientId: '443562001040-ds0g5shncqvsn1v6cfa2pj97edgdhl4l.apps.googleusercontent.com',
    iosBundleId: 'com.gechan.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbA700j-7nMDoi4JJlusKE2QV8sWBnBpw',
    appId: '1:443562001040:ios:87c03b12ceb8a938a88e15',
    messagingSenderId: '443562001040',
    projectId: 'flutter-my-app-d1f4c',
    storageBucket: 'flutter-my-app-d1f4c.appspot.com',
    iosClientId: '443562001040-uumb6u0rsrp7caj359a0r9mehrr9d8bq.apps.googleusercontent.com',
    iosBundleId: 'com.gechan.firebase.RunnerTests',
  );
}
